In [57]:
import pandas as pd

In [58]:
nyc_pd1 = pd.read_csv('data/201701-citibike-tripdata.csv')
nyc_pd2 = pd.read_csv('data/201702-citibike-tripdata.csv')
nyc_pd3 = pd.read_csv('data/201703-citibike-tripdata.csv')
nyc_pd4 = pd.read_csv('data/201704-citibike-tripdata.csv')
nyc_pd5 = pd.read_csv('data/201705-citibike-tripdata.csv')
nyc_pd6 = pd.read_csv('data/201706-citibike-tripdata.csv')
nyc_pd7 = pd.read_csv('data/201707-citibike-tripdata.csv')

In [137]:
nyc_pd5.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,254,2017-05-01 00:00:13,2017-05-01 00:04:27,511,E 14 St & Avenue B,40.729387,-73.977724,394,E 9 St & Avenue C,40.725213,-73.977688,27695,Subscriber,1996.0,2
1,248,2017-05-01 00:00:19,2017-05-01 00:04:28,511,E 14 St & Avenue B,40.729387,-73.977724,394,E 9 St & Avenue C,40.725213,-73.977688,15869,Subscriber,1996.0,1
2,1120,2017-05-01 00:00:19,2017-05-01 00:19:00,242,Carlton Ave & Flushing Ave,40.697787,-73.973736,3083,Bushwick Ave & Powers St,40.712477,-73.941000,18700,Subscriber,1985.0,2
3,212,2017-05-01 00:00:24,2017-05-01 00:03:56,168,W 18 St & 6 Ave,40.739713,-73.994564,116,W 17 St & 8 Ave,40.741776,-74.001497,24981,Subscriber,1993.0,1
4,686,2017-05-01 00:00:29,2017-05-01 00:11:55,494,W 26 St & 8 Ave,40.747348,-73.997236,527,E 33 St & 2 Ave,40.744023,-73.976056,25407,Subscriber,1964.0,1

In [103]:
nyc_pd1.columns = ['tripduration', 'starttime', 'stoptime', 'start station id', 'start station name', 'start station latitude',
             'start station longitude', 'end station id','end station name', 'end station latitude', 'end station longitude',
             'bikeid','usertype','birth year','gender']

In [30]:
nyc_pd1.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                 float64
gender                       int64
dtype: object

In [10]:
nyc_pd2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,364,2017-07-01 00:00:00,2017-07-01 00:06:05,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,14744,Subscriber,1986.0,1
1,2142,2017-07-01 00:00:03,2017-07-01 00:35:46,293,Lafayette St & E 8 St,40.730207,-73.991026,3425,2 Ave & E 104 St,40.789210,-73.943708,19587,Subscriber,1981.0,1
2,328,2017-07-01 00:00:08,2017-07-01 00:05:37,3242,Schermerhorn St & Court St,40.691029,-73.991834,3397,Court St & Nelson St,40.676395,-73.998699,27937,Subscriber,1984.0,2
3,2530,2017-07-01 00:00:11,2017-07-01 00:42:22,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,398,Atlantic Ave & Furman St,40.691652,-73.999979,26066,Subscriber,1985.0,1
4,2534,2017-07-01 00:00:15,2017-07-01 00:42:29,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,398,Atlantic Ave & Furman St,40.691652,-73.999979,29408,Subscriber,1982.0,2

In [11]:
nyc_pd3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1397,2017-06-01 00:00:02,2017-06-01 00:23:19,515,W 43 St & 10 Ave,40.760094,-73.994618,3285,W 87 St & Amsterdam Ave,40.788390,-73.974700,26642,Subscriber,1967.0,1
1,1103,2017-06-01 00:00:13,2017-06-01 00:18:37,488,W 39 St & 9 Ave,40.756458,-73.993722,297,E 15 St & 3 Ave,40.734232,-73.986923,25656,Subscriber,1981.0,1
2,1810,2017-06-01 00:00:20,2017-06-01 00:30:31,461,E 20 St & 2 Ave,40.735877,-73.982050,465,Broadway & W 41 St,40.755136,-73.986580,21023,Subscriber,1982.0,1
3,1760,2017-06-01 00:00:24,2017-06-01 00:29:45,2009,Catherine St & Monroe St,40.711174,-73.996826,527,E 33 St & 2 Ave,40.744023,-73.976056,25718,Subscriber,1973.0,2
4,2165,2017-06-01 00:00:33,2017-06-01 00:36:38,360,William St & Pine St,40.707179,-74.008873,474,5 Ave & E 29 St,40.745168,-73.986831,18691,Subscriber,1985.0,1

In [18]:
(nyc_pd1[nyc_pd1.isnull().any(axis=1)])

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
14,720,2017-08-01 00:01:38,2017-08-01 00:13:39,379,W 31 St & 7 Ave,40.749156,-73.991600,3466,W 45 St & 6 Ave,40.756687,-73.982577,18896,Customer,NaN,0
26,677,2017-08-01 00:02:24,2017-08-01 00:13:41,379,W 31 St & 7 Ave,40.749156,-73.991600,3466,W 45 St & 6 Ave,40.756687,-73.982577,14592,Customer,NaN,0
45,1878,2017-08-01 00:04:31,2017-08-01 00:35:49,3161,W 76 St & Columbus Ave,40.780184,-73.977285,503,E 20 St & Park Ave,40.738274,-73.987520,28613,Customer,NaN,0
47,1879,2017-08-01 00:04:38,2017-08-01 00:35:58,3161,W 76 St & Columbus Ave,40.780184,-73.977285,503,E 20 St & Park Ave,40.738274,-73.987520,17597,Customer,NaN,0
54,1449,2017-08-01 00:05:55,2017-08-01 00:30:04,412,Forsyth St & Canal St,40.715816,-73.994224,519,Pershing Square North,40.751873,-73.977706,16488,Customer,NaN,0
55,554,2017-08-01 00:05:59,2017-08-01 00:15:14,72,W 52 St & 11 Ave,40.767272,-73.993929,448,W 37 St & 10 Ave,40.756604,-73.997901,18521,Customer,NaN,0
57,1363,2017-08-01 00:06:04,2017-08-01 00:28:47,3260,Mercer St & Bleecker St,40.727064,-73.996621,471,Grand St & Havemeyer St,40.712868,-73.956981,20783,Customer,NaN,0
66,1393,2017-08-01 00:06:53,2017-08-01 00:30:07,412,Forsyth St & Canal St,40.715816,-73.994224,519,Pershing Square North,40.751873,-73.977706,25602,Customer,NaN,0
94,5795,2017-08-01 00:09:25,2017-08-01 01:46:01,2006,Central Park S & 6 Ave,40.765909,-73.976342,500,Broadway & W 51 St,40.762288,-73.983362,28040,Customer,NaN,0
98,1085,2017-08-01 00:09:57,2017-08-01 00:28:03,504,1 Ave & E 16 St,40.732219,-73.981656,291,Madison St & Montgomery St,40.713126,-73.984844,27048,Subscriber,NaN,0
110,2749,2017-08-01 00:10:51,2017-08-01 00:56:41,460,S 4 St & Wythe Ave,40.712859,-73.965903,174,E 25 St & 1 Ave,40.738177,-73.977387,27817,Customer,NaN,0
111,2734,2017-08-01 00:10:51,2017-08-01 00:56:25,460,S 4 St & Wythe Ave,40.712859,-73.965903,174,E 25 St & 1 Ave,40.738177,-73.977387,26389,Customer,NaN,0
122,1243,2017-08-01 00:12:45,2017-08-01 00:33:28,325,E 19 St & 3 Ave,40.736245,-73.984738,444,Broadway & W 24 St,40.742354,-73.989151,29752,Customer,NaN,0
127,1228,2017-08-01 00:12:59,2017-08-01 00:33:27,325,E 19 St & 3 Ave,40.736245,-73.984738,444,Broadway & W 24 St,40.742354,-73.989151,25768,Customer,NaN,0
143,1052,2017-08-01 00:14:51,2017-08-01 00:32:23,3469,India St & West St,40.731814,-73.959950,3103,N 11 St & Wythe Ave,40.721533,-73.957824,16583,Customer,NaN,0
144,1583,2017-08-01 00:14:59,2017-08-01 00:41:22,450,W 49 St & 8 Ave,40.762272,-73.987882,3224,W 13 St & Hudson St,40.739974,-74.005139,28610,Customer,NaN,0
145,1316,2017-08-01 00:15:04,2017-08-01 00:37:00,450,W 49 St & 8 Ave,40.762272,-73.987882,405,Washington St & Gansevoort St,40.739323,-74.008119,26730,Customer,NaN,0
146,1245,2017-08-01 00:15:07,2017-08-01 00:35:53,450,W 49 St & 8 Ave,40.762272,-73.987882,405,Washington St & Gansevoort St,40.739323,-74.008119,28119,Customer,NaN,0
153,1004,2017-08-01 00:16:13,2017-08-01 00:32:58,401,Allen St & Rivington St,40.720196,-73.989978,474,5 Ave & E 29 St,40.745168,-73.986831,17601,Customer,NaN,0
166,352,2017-08-01 00:17:43,2017-08-01 00:23:36,438,St Marks Pl & 1 Ave,40.727791,-73.985649,473,Rivington St & Chrystie St,40.721101,-73.991925,19083,Customer,NaN,0
172,704,2017-08-01 00:18:30,2017-08-01 00:30:15,3466,W 45 St & 6 Ave,40.756687,-73.982577,3164,Columbus Ave & W 72 St,40.777057,-73.978985,18896,Customer,NaN,0
181,5246,2017-08-01 00:19:12,2017-08-01 01:46:39,2006,Central Park S & 6 Ave,40.765909,-73.976342,500,Broadway & W 51 St,40.762288,-73.983362,29009,Customer,NaN,0
191,1928,2017-08-01 00:20:26,2017-08-01 00:52:34,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,3463,E 16 St & Irving Pl,40.735367,-73.987974,19245,Customer,NaN,0
197,1949,2017-08-01 00:22:11,2017-08-01 00:54:40,3466,W 45 St & 6 Ave,40.756687,-73.982577,531,Forsyth St & Broome St,40.718939,-73.992663,14592,Customer,NaN,0
214,1726,2017-08-01 00:25:11,2017-08-01 00:53:58,369,Washington Pl & 6 Ave,40.732241,-74.000264,3397,Court St & Nelson St,40.676395,-73.998699,30322,Subscriber,NaN,0
215,652,2017-08-01 00:25:23,2017-08-01 00:36:15,3427,Lafayette St & Jersey St,40.724305,-73.996010,380,W 4 St & 7 Ave S,40.734011,-74.002939,27712,Customer,NaN,0
231,947,2017-08-01 00:28:34,2017-08-01 00:44:22,3429,Hanson Pl & Ashland Pl,40.685068,-73.977908,3042,Fulton St & Utica Ave,40.679427,-73.929891,19364,Subscriber,NaN,1
255,3101,2017-08-01 00:32:12,2017-08-01 01:23:54,217,Old Fulton St,40.702772,-73.993836,319,Fulton St & Broadway,40.711066,-74.009447,19193,Customer,NaN,0
256,1567,2017-08-01 00:32:30,2017-08-01 00:58:37,380,W 4 St & 7 Ave S,40.734011,-74.002939,532,S 5 Pl & S 4 St,40.710451,-73.960876,19082,Customer,NaN,0
258,1569,2017-08-01 00:32:36,2017-08-01 00:58:46,380,W 4 St & 7 Ave S,40.734011,-74.002939,532,S 5 Pl & S 4 St,40.710451,-73.960876,15522,Customer,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1816182,423,2017-08-31 23:35:24,2017-08-31 23:42:27,383,Greenwich Ave & Charles St,40.735238,-74.000271,462,W 22 St & 10 Ave,40.746920,-74.004519,26824,Subscriber,NaN,0
1816185,1231,2017-08-31 23:35:31,2017-08-31 23:56:02,529,W 42 St & 8 Ave,40.757570,-73.990985,3263,Cooper Square & E 7 St,40.729236,-73.990868,14722,Customer,NaN,0
1816203,1663,2017-08-31 23:37:09,2017-09-01 00:04:52,368,Carmine St & 6 Ave,40.730386,-74.002150,498,Broadway & W 32 St,40.748549,-73.988084,28398,Customer,NaN,0
1816214,858,2017-08-31 23:38:06,2017-08-31 23:52:24,476,E 31 St & 3 Ave,40.743943,-73.979661,3223,E 55 St & 3 Ave,40.758997,-73.968654,19767,Customer,NaN,0
1816222,1598,2017-08-31 23:38:19,2017-09-01 00:04:57,368,Carmine St & 6 Ave,40.730386,-74.002150,498,Broadway & W 32 St,40.748549,-73.988084,29432,Customer,NaN,0
1816234,756,2017-08-31 23:39:12,2017-08-31 23:51:48,265,Stanton St & Chrystie St,40.722293,-73.991475,476,E 31 St & 3 Ave,40.743943,-73.979661,28595,Subscriber,NaN,0
1816243,1533,2017-08-31 23:39:44,2017-09-01 00:05:17,514,12 Ave & W 40 St,40.760875,-74.002777,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,21518,Customer,NaN,0
1816244,1526,2017-08-31 23:39:45,2017-09-01 00:05:11,514,12 Ave & W 40 St,40.760875,-74.002777,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,14856,Customer,NaN,0
1816248,1507,2017-08-31 23:40:03,2017-09-01 00:05:10,514,12 Ave & W 40 St,40.760875,-74.002777,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,25644,Customer,NaN,0
1816253,1465,2017-08-31 23:40:44,2017-09-01 00:05:09,514,12 Ave & W 40 St,40.760875,-74.002777,3256,Pier 40 - Hudson River Park,40.727714,-74.011296,21585,Customer,NaN,0
1816256,655,2017-08-31 23:41:16,2017-08-31 23:52:12,285,Broadway & E 14 St,40.734546,-73.990741,3427,Lafayette St & Jersey St,40.724305,-73.996010,25413,Customer,NaN,0
1816264,581,2017-08-31 23:41:40,2017-08-31 23:51:22,428,E 3 St & 1 Ave,40.724677,-73.987834,2012,E 27 St & 1 Ave,40.739445,-73.976806,29699,Subscriber,NaN,0
1816271,653,2017-08-31 23:42:06,2017-08-31 23:52:59,438,St Marks Pl & 1 Ave,40.727791,-73.985649,128,MacDougal St & Prince St,40.727103,-74.002971,21711,Customer,NaN,0
1816273,661,2017-08-31 23:42:07,2017-08-31 23:53:09,438,St Marks Pl & 1 Ave,40.727791,-73.985649,128,MacDougal St & Prince St,40.727103,-74.002971,19809,Customer,NaN,0
1816293,634,2017-08-31 23:43:11,2017-08-31 23:53:45,2021,W 45 St & 8 Ave,40.759291,-73.988597,449,W 52 St & 9 Ave,40.764618,-73.987895,28424,Customer,NaN,0
1816295,598,2017-08-31 23:43:19,2017-08-31 23:53:17,2021,W 45 St & 8 Ave,40.759291,-73.988597,449,W 52 St & 9 Ave,40.764618,-73.987895,19002,Customer,NaN,0
1816360,1043,2017-08-31 23:49:33,2017-09-01 00:06:56,335,Washington Pl & Broadway,40.729039,-73.994046,474,5 Ave & E 29 St,40.745168,-73.986831,19293,Customer,NaN,0
1816370,1005,2017-08-31 23:50:07,2017-09-01 00:06:52,335,Washington Pl & Broadway,40.729039,-73.994046,474,5 Ave & E 29 St,40.745168,-73.986831,20526,Customer,NaN,0
1816385,387,2017-08-31 23:51:36,2017-08-31 23:58:04,3122,48 Ave & 5 St,40.744363,-73.955873,3126,44 Dr & Jackson Ave,40.747182,-73.943264,21155,Customer,NaN,0
1816396,417,2017-08-31 23:52:29,2017-08-31 23:59:27,3407,Union St & Nevins St,40.679098,-73.987655,3398,Smith St & 9 St,40.674696,-73.997858,27985,Customer,NaN,0
1816403,123,2017-08-31 23:52:54,2017-08-31 23:54:58,3244,University Pl & E 8 St,40.731437,-73.994903,293,Lafayette St & E 8 St,40.730207,-73.991026,27563,Customer,NaN,0
1816416,1340,2017-08-31 23:54:05,2017-09-01 00:16:26,157,Henry St & Atlantic Ave,40.690893,-73.996123,3405,5 St & 6 Ave,40.670484,-73.982090,18594,Customer,NaN,0
1816424,1291,2017-08-31 23:54:45,2017-09-01 00:16:17,157,Henry St & Atlantic Ave,40.690893,-73.996123,3405,5 St & 6 Ave,40.670484,-73.982090,17136,Customer,NaN,0
1816426,952,2017-08-31 23:54:48,2017-09-01 00:10:41,245,Myrtle Ave & St Edwards St,40.693270,-73.977039,3061,Throop Ave & Myrtle Ave,40.696229,-73.943711,15167,Customer,NaN,0
1816427,942,2017-08-31 23:54:49,2017-09-01 00:10:31,245,Myrtle Ave & St Edwards St,40.693270,-73.977039,3061,Throop Ave & Myrtle Ave,40.696229,-73.943711,21100,Customer,NaN,0
1816437,738,2017-08-31 23:55:27,2017-09-01 00:07:45,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,3080,S 4 St & Rodney St,40.709340,-73.956080,17288,Subscriber,NaN,0
1816444,648,2017-08-31 23:56:03,2017-09-01 00:06:52,3147,E 85 St & 3 Ave,40.778012,-73.954071,3147,E 85 St & 3 Ave,40.778012,-73.954071,18834,Subscriber,NaN,0
1816478,1367,2017-08-31 23:59:05,2017-09-01 00:21:53,3263,Cooper Square & E 7 St,40.729236,-73.990868,265,Stanton St & Chrystie St,40.722293,-73.991475,19123,Customer,NaN,0
1816481,332,2017-08-31 23:59:22,2017-09-01 00:04:54,3364,Carroll St & 5 Ave,40.675162,-73.981483,3313,6 Ave & 12 St,40.666318,-73.985462,30471,Subscriber,NaN,0
1816487,510,2017-08-31 23:59:52,2017-09-01 00:08:22,267,Broadway & W 36 St,40.750977,-73.987654,382,University Pl & E 14 St,40.734927,-73.992005,29071,Customer,NaN,0

In [138]:
csv_final.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,254,2017-05-01 00:00:13,2017-05-01 00:04:27,511,E 14 St & Avenue B,40.729387,-73.977724,394,E 9 St & Avenue C,40.725213,-73.977688,27695,Subscriber,1996.0,2
1,248,2017-05-01 00:00:19,2017-05-01 00:04:28,511,E 14 St & Avenue B,40.729387,-73.977724,394,E 9 St & Avenue C,40.725213,-73.977688,15869,Subscriber,1996.0,1
2,1120,2017-05-01 00:00:19,2017-05-01 00:19:00,242,Carlton Ave & Flushing Ave,40.697787,-73.973736,3083,Bushwick Ave & Powers St,40.712477,-73.941000,18700,Subscriber,1985.0,2
3,212,2017-05-01 00:00:24,2017-05-01 00:03:56,168,W 18 St & 6 Ave,40.739713,-73.994564,116,W 17 St & 8 Ave,40.741776,-74.001497,24981,Subscriber,1993.0,1
4,686,2017-05-01 00:00:29,2017-05-01 00:11:55,494,W 26 St & 8 Ave,40.747348,-73.997236,527,E 33 St & 2 Ave,40.744023,-73.976056,25407,Subscriber,1964.0,1

In [141]:
csv_final = nyc_pd6.append(nyc_pd7)

In [116]:
csv_final = csv_final.append(nyc_pd3)

In [117]:
csv_final = csv_final.append(nyc_pd4)

In [118]:
csv_final = csv_final.append(nyc_pd5)

In [119]:
csv_final = csv_final.append(nyc_pd6)

In [132]:
csv_final = csv_final.append(nyc_pd7)

In [143]:
csv_final = csv_final.append(nyc_pd8)

In [139]:
csv_final_df.to_csv('output1.csv')

In [140]:
nyc_pd5.to_csv('nyc_pd5_citibikes.csv')

In [129]:
nyc_pd4.to_csv('nyc_pd4_citibikes.csv')